application_front:
    resource: "@ApplicationFrontBundle/Controller/"
    type:     annotation
    prefix:   /
#    defaults: { _controller: ApplicationFrontBundle:Default:login}

#fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_welcome:
    pattern:  /
    defaults: { _controller: ApplicationFrontBundle:Default:index}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout}

login:
    path: /login
    defaults: { _controller: ApplicationFrontBundle:Default:login}

login_check:
    path: /login_check
    defaults: { _controller: ApplicationFrontBundle:Default:check}
    
signup:
    path: /signup
    defaults: { _controller: ApplicationFrontBundle:Default:signup}
