application_front:
    resource: "@ApplicationFrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_welcome:
    pattern:  /
    defaults: { _controller: FOSUserBundle:Security:login} 
