security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CATALOGER:         [ROLE_USER]
        ROLE_MANAGER:           [ROLE_CATALOGER]
        ROLE_ADMIN:             [ROLE_MANAGER]
        ROLE_SUPER_ADMIN:       [ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                always_use_default_target_path: false
                check_path: /login_check
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/signup, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^check-email, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^confirm/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^confirmed, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
        - { path: ^/users, role: ROLE_MANAGER }
        - { path: ^/jobs, role: ROLE_SUPER_ADMIN }
        - { path: ^/organizations/new, role: ROLE_SUPER_ADMIN }
        - { path: ^/organizations, role: ROLE_MANAGER }
        - { path: ^/projects/$, role: ROLE_USER }
        - { path: ^/projects/, role: ROLE_MANAGER }
        - { path: ^/vocabularies/, role: ROLE_SUPER_ADMIN }
        - { path: ^/fieldsettings, role: ROLE_MANAGER }
        - { path: ^/record/$, role: ROLE_USER }
        - { path: ^/record/, role: ROLE_USER }
        - { path: ^/report/, role: ROLE_USER }
        - { path: ^/, role: ROLE_USER }



    acl:
        connection: default
